config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web => '/sidekiq'

  root "urls#index"

  resources :urls do
    collection do
      delete :delete_all
    end
  end

  get '/dashboard', to: 'urls#show', as: :show_urls
  get '/:short_url', to: 'urls#redirect', as: :short_link


  resources :users


  get "/auth/logout", to: "sessions#destroy"
  get "auth/login", to: "sessions#new"
  post "/auth/login", to: "sessions#create"
  get '/auth/signup', to: 'users#new'
  post "auth/signup", to: "users#create"





  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/url.rb
class Url < ApplicationRecord
  belongs_to :user

  before_validation :generate_short_url

  validates :original_url, presence: { message: "Enter a valid link" }, format: { with: URI::regexp(%w[http https]), message: "Not a valid URL" }
  validates :short_url, uniqueness: { message: "is already taken" }, length: { maximum: 8, message: "is too long (maximum is 8 characters)" }

  HUMANIZED_ATTRIBUTES = {
    original_url: "",
    short_url: "Alias"
  }

  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  def short_link
    Rails.application.routes.url_helpers.short_link_url(self.short_url, host: 'http://localhost:3000')
  end

  def generate_short_url
    self.short_url = SecureRandom.hex(4) if self.short_url.nil? || self.short_url.empty?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :urls, dependent: :destroy

  before_save :downcase

  has_secure_password

  validates :username,
            presence: {
              message: "can't be blank",
            },
            uniqueness: {
              message: 'is already taken',
            }
  validates :email,
            presence: {
              message: "can't be blank",
            },
            uniqueness: {
              message: 'is already taken',
            }
  validates_format_of :email,
                      with: URI::MailTo::EMAIL_REGEXP,
                      message: 'Invalid email format'

  HUMANIZED_ATTRIBUTES = {
    username: 'Username',
    email: 'Email',
    password_digest: 'Password',
  }

  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  def downcase
    self.email = email.downcase
    self.username = username.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticated

end

app/controllers/concerns/authenticated.rb
module Authenticated
  extend ActiveSupport::Concern

  included do
    before_action :current_user
    helper_method :current_user
    helper_method :user_signed_in?
  end

  def login(user)
    reset_session
    session[:current_user_id] = user.id
  end

  def logout
    reset_session
  end

  def redirect_if_authenticated
    redirect_to root_path, alert: "You are already logged in." if user_signed_in?
  end

  def require_login
    unless current_user
      flash[:alert] = 'Please login to access this page.'
      redirect_to auth_login_url
    end
  end

  private

  def current_user
    Current.user ||= session[:current_user_id] && User.find_by(id: session[:current_user_id])
  end

  def user_signed_in?
    Current.user.present?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :redirect_if_authenticated, only: [:create, :new]

  def new
    redirect_to root_path if current_user
  end

  def create
    @user = User.find_by(email: user_params[:email])

    if @user && @user.authenticate(user_params[:password])
      login @user
      redirect_to root_path, notice: "Signed in"
    else
      flash.now[:alert] = "Incorrect email or password"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to auth_login_url, notice: 'Logged out successfully!'
  end


  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  before_action :require_login

  def index
    @url = Url.new
    @short_link = params[:short_link]
    @original_url = params[:original_url]
    @short_url = params[:short_url]
  end

  def create
    @url = current_user.urls.build(url_params)

    if @url.save
      @original_url = @url.original_url
      @short_link = @url.short_link
      @short_url = @url.short_url
      LinkStatisticsJob.set(wait: 2.hours).perform_later(current_user.id) if current_user.urls.count == 1
      redirect_to root_path(short_link: @url.short_link, original_url: @url.original_url, short_url: @url.short_url), notice: 'URL was successfully created.'
    else
      render :index, status: :unprocessable_entity
    end
  end


  def show
    @urls = current_user.urls
  end

  def destroy
    @url = Url.find_by(id: params[:id])
    @url.destroy
    redirect_to show_urls_path, notice: 'Link was successfully deleted.'
  end

  def redirect
    @url = Url.find_by(short_url: params[:short_url])
    if @url
      @url.update_attribute(:click, @url.click.to_i + 1)
      redirect_to @url.original_url, allow_other_host: true
    else
      redirect_to root_path, status: 404
    end
  end

  def delete_all
    current_user.urls.destroy_all
    redirect_to show_urls_path, notice: 'Links deleted successfully'
  end


  # Strong parameters to filter params and specify params that are allowed
  private
  def url_params
    params.require(:url).permit(:original_url, :short_url, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :redirect_if_authenticated

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      WelcomeJob.perform_async(@user.id, @user.username, @user.email)

      redirect_to auth_login_url, notice: 'Successfully registered!'
    else
      render :new, status: :unprocessable_entity
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class
    case flash.keys.first.to_sym
    when :notice
      'bg-green-200 text-green-800 border-green-400'
    when :alert
      'bg-error text-red-800 border-red-400'
    else
      'bg-gray-200 text-gray-800 border-gray-400'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%=
      stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload'
    %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%=
      stylesheet_link_tag 'application',
                          :media => 'all',
                          'data-turbolinks-track' => true
    %>
    <%= javascript_importmap_tags %>
    <script>
      if (performance.navigation.type === 1) {
        window.location.href =
          window.location.origin + window.location.pathname;
      }
    </script>
  </head>
  <body class="flex flex-col min-h-screen bg-main">
    <%= render 'shared/navbar' %>
    <div class="container mx-auto mt-4 p-2 flex flex-col relative">
      <% flash.each do |type, msg| %>
        <div
          class="<%= flash_class %> absolute top-0 left-1/2 transform -translate-x-1/2 max-w-md mx-auto text-center px-4 py-2 rounded mb-4 flash-message opacity-100 transition-opacity duration-300 sm:w-full md:w-2/3 lg:w-1/2 xl:w-1/3"
        >
          <%= msg %>
          <script>
            setTimeout(function () {
              var flashMessage = document.querySelector(".flash-message");
              flashMessage.style.opacity = "0";
              setTimeout(function () {
                flashMessage.style.display = "none";
              }, 300);
            }, 3000);
          </script>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<!-- Main Navbar -->
<nav class="relative px-4 py-4 flex justify-between items-center" data-turbo-action="replace">
  <div class="text-base font-bold leading-none">
    <%= link_to root_path, class: "flex items-center text-white", 'data-turbo-action': 'replace' do %>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 576 512"
        class="w-6 h-6"
      >
        <path
          d="M320 96a32 32 0 1 1 -64 0 32 32 0 1 1 64 0zm21.1 80C367 158.8 384 129.4 384 96c0-53-43-96-96-96s-96 43-96 96c0 33.4 17 62.8 42.9 80H224c-17.7 0-32 14.3-32 32s14.3 32 32 32h32V448H208c-53 0-96-43-96-96v-6.1l7 7c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9L97 263c-9.4-9.4-24.6-9.4-33.9 0L7 319c-9.4 9.4-9.4 24.6 0 33.9s24.6 9.4 33.9 0l7-7V352c0 88.4 71.6 160 160 160h80 80c88.4 0 160-71.6 160-160v-6.1l7 7c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-56-56c-9.4-9.4-24.6-9.4-33.9 0l-56 56c-9.4 9.4-9.4 24.6 0 33.9s24.6 9.4 33.9 0l7-7V352c0 53-43 96-96 96H320V240h32c17.7 0 32-14.3 32-32s-14.3-32-32-32H341.1z"
          fill="white"
        />
      </svg>
      <span class="ml-4">Home</span>
    <% end %>
  </div>
  <div class="lg:hidden">
    <button id="navbar-toggle" class="navbar-burger flex items-center text-white p-4" data-turbo-action="replace">
      <svg
        class="block h-6 w-6"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" fill="white"></path>
      </svg>
    </button>
  </div>

  <% if user_signed_in? %>
    <%= link_to 'Dashboard', show_urls_path, class: "hidden lg:inline-block lg:ml-auto lg:mr-3 py-2 px-6 bg-gray-50 hover:bg-gray-100 text-sm text-secondary font-bold  rounded-xl transition duration-200", 'data-turbo-action': 'replace' %>
    <%= link_to 'Signout', auth_logout_path, class: "hidden lg:inline-block py-2 px-6 bg-secondary hover:bg-custom-pink text-sm text-white font-bold rounded-xl transition duration-200", 'data-turbo-action': 'replace' %>
  <% else %>
    <%= link_to 'Sign In', auth_login_url, class: "hidden lg:inline-block lg:ml-auto lg:mr-3 py-2 px-6 bg-gray-50 hover:bg-gray-100 text-sm text-gray-900 font-bold rounded-xl transition duration-200", 'data-turbo-action': 'replace' %>
    <%= link_to 'Sign Up', auth_signup_path, class: "hidden lg:inline-block py-2 px-6 bg-secondary hover:bg-custom-pink text-sm text-white font-bold rounded-xl transition duration-200", 'data-turbo-action': 'replace' %>
  <% end %>
</nav>

<!-- Mobile Navbar -->
<div class="navbar-menu relative z-50 hidden" data-turbo-action="replace">
  <div class="navbar-backdrop fixed inset-0 bg-gray-800 opacity-25"></div>
  <nav
    class="fixed top-0 right-0 bottom-0 flex flex-col w-5/6 max-w-sm py-6 px-6 bg-white border-r overflow-y-auto"
    id="navbar-menu"
  >
    <div class="flex items-center mb-8">
      <div class="text-3xl font-bold leading-none">
        <%= link_to root_path, class: "flex items-center text-white", 'data-turbo-action': 'replace' do %>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 576 512"
            class="w-6 h-6"
          >
            <path
              d="M320 96a32 32 0 1 1 -64 0 32 32 0 1 1 64 0zm21.1 80C367 158.8 384 129.4 384 96c0-53-43-96-96-96s-96 43-96 96c0 33.4 17 62.8 42.9 80H224c-17.7 0-32 14.3-32 32s14.3 32 32 32h32V448H208c-53 0-96-43-96-96v-6.1l7 7c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9L97 263c-9.4-9.4-24.6-9.4-33.9 0L7 319c-9.4 9.4-9.4 24.6 0 33.9s24.6 9.4 33.9 0l7-7V352c0 88.4 71.6 160 160 160h80 80c88.4 0 160-71.6 160-160v-6.1l7 7c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-56-56c-9.4-9.4-24.6-9.4-33.9 0l-56 56c-9.4 9.4-9.4 24.6 0 33.9s24.6 9.4 33.9 0l7-7V352c0 53-43 96-96 96H320V240h32c17.7 0 32-14.3 32-32s-14.3-32-32-32H341.1z"
              fill="white"
            />
          </svg>
          <span class="ml-4">Home</span>
        <% end %>
      </div>
      <button id="navbar-close" class="navbar-close">
        <svg
          class="h-6 w-6 text-gray-400 cursor-pointer hover:text-gray-500"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M6 18L18 6M6 6l12 12"
          ></path>
        </svg>
      </button>
    </div>

    <div class="mt-4">
      <div class="pt-6">
        <% if user_signed_in? %>
          <%= link_to 'Dashboard', show_urls_path, class: "block px-4 py-3 mb-3 leading-loose text-xs text-center bg-gray-50 hover:bg-gray-100 text-sm text-secondary font-semibold rounded-xl transition duration-200 leading-none", 'data-turbo-action': 'replace' %>
          <%= link_to 'Signout', auth_logout_path, class: "block px-4 py-3 mb-2 leading-loose text-xs text-center text-white font-semibold bg-secondary hover:bg-pink-400  rounded-xl", 'data-turbo-action': 'replace' %>
        <% else %>
          <%= link_to 'Sign In', auth_login_url, class: "block px-4 py-3 mb-3 leading-loose text-xs text-center font-semibold leading-none bg-gray-50 hover:bg-gray-100 text-sm text-gray-900 font-bold rounded-xl transition duration-200", 'data-turbo-action': 'replace' %>
          <%= link_to 'Sign Up', auth_signup_path, class: "block px-4 py-3 mb-2 leading-loose text-xs text-center text-white font-semibold bg-secondary hover:bg-pink-400  rounded-xl", 'data-turbo-action': 'replace' %>
        <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/urls/show.html.erb
<div class="flex flex-col">
  <div class="flex items-center mb-4">
<h2 class="text-lg sm:text-xl md:text-2xl lg:text-3xl text-white font-bold mb-2">
  Hello, <%= current_user.username.capitalize %>
</h2>
    <%= image_tag('wave.png', class: 'h-6 w-auto', alt: 'wave') %>
  </div>
  <% if @urls.present? %>
    <p class="text-lg mb-8 text-secondary font-medium">
      Track your links below:
    </p>
    <div
      class="overflow-x-auto sm:-mx-6 lg:-mx-8 rounded-lg shadow-lg border-t-4 border-secondary bg-white min-w-full"
    >
      <table
        class="min-w-full py-2 sm:px-6 lg:px-8 text-left text-sm font-light"
      >
        <thead
          class="border-b bg-white font-medium dark:border-neutral-500 dark:bg-neutral-600"
        >
          <tr>
            <th scope="col" class="px-6 py-4">#</th>
            <th scope="col" class="px-6 py-4">Original URL</th>
            <th scope="col" class="px-6 py-4">Short URL</th>
            <th scope="col" class="px-6 py-4">Clicks</th>
            <th scope="col" class="px-6 py-4">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @urls.each_with_index do |url, index| %>
            <tr
              class="<%=
  if index.odd?
    'bg-neutral-100 dark:bg-neutral-700'
  else
    'bg-white dark:bg-neutral-600'
  end
%>"
            >
              <td class="whitespace-nowrap px-6 py-4 font-medium">
                <%= index + 1 %>
              </td>
              <td
                class="whitespace-nowrap px-6 py-4 overflow-hidden overflow-ellipsis max-w-[200px]"
              >
                <%= url.original_url %>
              </td>
              <td class="whitespace-nowrap px-6 py-4">
                <%= url.short_link %>
              </td>
              <td class="whitespace-nowrap px-6 py-4">
                <%= url.click || 0 %>
              </td>
              <td class="whitespace-nowrap px-6 py-4">
                <div class="flex gap-1 justify-between">
                  <%= link_to short_link_url(short_url: url.short_url), target: "_blank", class: "text-blue-600 hover:underline" do %>
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke-width="1.5"
                      stroke="currentColor"
                      class="w-6 h-6"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25"
                      />
                    </svg>
                  <% end %>
                  <div data-controller="clipboard">
                    <input
                      data-clipboard-target="source"
                      class="font-extralight text-xs h-6 rounded-md hidden"
                      type="text"
                      value="<%= url.short_link %>"
                      readonly
                    />
                    <button
                      data-clipboard-target="trigger"
                      data-action="clipboard#copy"
                    >
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        class="w-6 h-6"
                        data-target="clipboard.icon"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 13.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25ZM6.75 12h.008v.008H6.75V12Zm0 3h.008v.008H6.75V15Zm0 3h.008v.008H6.75V18Z"
                        />
                      </svg>
                    </button>
                  </div>
                  <%= link_to url_path(url), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-red-600 hover:text-red-800" do %>
                    <svg
                      class="h-6 w-6"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 448 512"
                    >
                      <path
                        d="M170.5 51.6L151.5 80h145l-19-28.4c-1.5-2.2-4-3.6-6.7-3.6H177.1c-2.7 0-5.2 1.3-6.7 3.6zm147-26.6L354.2 80H368h48 8c13.3 0 24 10.7 24 24s-10.7 24-24 24h-8V432c0 44.2-35.8 80-80 80H112c-44.2 0-80-35.8-80-80V128H24c-13.3 0-24-10.7-24-24S10.7 80 24 80h8H80 93.8l36.7-55.1C140.9 9.4 158.4 0 177.1 0h93.7c18.7 0 36.2 9.4 46.6 24.9zM80 128V432c0 17.7 14.3 32 32 32H336c17.7 0 32-14.3 32-32V128H80zm80 64V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16zm80 0V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16zm80 0V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16z"
                        fill="#BD3A4A"
                      />
                    </svg>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%=
      link_to 'Delete All',
              delete_all_urls_path,
              class: 'text-red-600 hover:text-red-800',
              method: :delete,
              data: {
                turbo_method: :delete,
                turbo_confirm: 'Are you sure?',
              }
    %>
  <% else %>
    <div class="flex flex-col items-center justify-center">
      <%= image_tag 'nothing-yet2.png', class: 'max-w-full h-auto mb-4 mt-4' %>
      <p class="text-white text-center">You haven't generated any links yet.</p>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <%= image_tag("rocket.svg", class: "mx-auto h-20 w-auto", alt: "SnappyUrl") %>
    <h2 class="mt-4 text-center text-3xl font-bold leading-9 tracking-tight text-secondary">Join us today!</h2>
    <p class="text-base text-center mt-3 text-white">
      Shorten and share your links in a snap!
    </p>
  </div>

  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white p-6 rounded shadow-md">
 <%= form_with model: @user, url: auth_signup_url do |form| %>
      <div class="mb-4">
        <%= form.label :username, class: "block text-sm font-medium leading-6 text-balance" %>
        <div class="mt-2">
          <%= form.text_field :username, autocomplete: "username", class: "block w-full rounded-md border-0 bg-white/5 py-1.5 text-gray-800 shadow-sm ring-1 ring-inset ring-secondary focus:ring-2 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6" %>
        </div>
        <% @user.errors.full_messages_for(:username).each do |message| %>
          <div class="text-secondary mt-2 text-sm"><%= message %></div>
        <% end %>
      </div>

      <div class="mb-4">
        <%= form.label :email, class: "block text-sm font-medium leading-6 text-balance" %>
        <div class="mt-2">
          <%= form.email_field :email, autocomplete: "email", class: "block w-full rounded-md border-0 bg-white/5 py-1.5 text-gray-800 shadow-sm ring-1 ring-inset ring-secondary focus:ring-2 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6" %>
        </div>
        <% @user.errors.full_messages_for(:email).each do |message| %>
          <div class="text-secondary mt-2 text-sm"><%= message %></div>
        <% end %>
      </div>

      <div class="mb-4">
        <%= form.label :password, class: "block text-sm font-medium leading-6 text-black" %>
        <div class="mt-2">
          <%= form.password_field :password, class: "block w-full rounded-md border-0 bg-white/5 py-1.5 text-gray-800 shadow-sm ring-1 ring-inset ring-secondary focus:ring-2 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6" %>
          <% @user.errors.full_messages_for(:password).each do |message| %>
            <div class="text-secondary mt-2 text-sm"><%= message %></div>
          <% end %>
        </div>
      </div>

      <div class="mb-4">
        <%= form.label :password_confirmation, class: "block text-sm font-medium leading-6 text-black" %>
        <div class="mt-2">
          <%= form.password_field :password_confirmation, class: "block w-full rounded-md border-0 bg-white/5 py-1.5 text-gray-800 shadow-sm ring-1 ring-inset ring-secondary focus:ring-2 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6" %>
          <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
            <div class="text-secondary mt-2 text-sm"><%= message %></div>
          <% end %>
        </div>
      </div>

      <div class="mb-4">
        <%= form.submit "Sign up", class: "flex w-full cursor-pointer justify-center rounded-md bg-secondary px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-red-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-secondary" %>
      </div>
    <% end %>

    <p class="mt-4 text-center text-sm">
      Already a member?
      <%= link_to "Sign in", auth_login_url, class: "font-semibold leading-6 text-secondary hover:text-red-400" %>
    </p>
    </div>
   
  </div>
</div>